version: '3.4'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "200k"
    max-file: "10"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=paymentdb
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    logging: *default-logging
